version: '3.7'

services:
  client:
    build:
      context: ./services/client
      dockerfile: Dockerfile-dev
    volumes:
      - './services/client:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - 3007:3000
    env_file:
      - ./services/client/.env
    environment:
      - NODE_ENV=development
  playlists:
    build:
      context: ./services/playlists
      dockerfile: Dockerfile-dev
    volumes:
      - './services/playlists:/usr/src/app'
    ports:
      - 5001:5000
    env_file:
      - ./services/playlists/.env
    environment:
      - FLASK_APP=playlistviz.py
      - FLASK_ENV=development
      - APP_SETTINGS=app.config.DevConfig
