version: '3.7'

services:
  playlists:
    build:
      context: ./services/playlists
      dockerfile: Dockerfile-dev
    volumes:
      - './services/playlists:/usr/src/app'
    ports:
        - 5001:5000
    env_file:
      - ./.env
    environment:
      - FLASK_APP=playlistviz.py
      - FLASK_ENV=development
      - APP_SETTINGS=app.config.DevConfig
