# base image
FROM node:11.12.0-alpine

# set working directory
WORKDIR /usr/src/app

ENV PATH /usr/src/app/node_modules/.bin:$PATH

# install and cache app dependencies
COPY package.json /usr/src/app/package.json
COPY package-lock.json /usr/src/app/package-lock.json
COPY webpack.dev.js /usr/src/app/webpack.dev.js

#install packages
RUN npm install

# start app
CMD ["npm", "run", "start"]
